/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.guruz.p300.windowui.panels;

import de.guruz.p300.Configuration;
import de.guruz.p300.MainDialog;

/**
 *
 * @author Leo
 */
public class PasswordConfigurationPanel extends javax.swing.JPanel {

    /**
     * Creates new form PasswordConfigurationPanel2
     */
    public PasswordConfigurationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        resetadminpasswordbutton = new javax.swing.JButton();
        getadminpasswordButton = new javax.swing.JButton();
        passwordField = new javax.swing.JTextField();

        jLabel1.setText("This password allows you to connect to a p300 server remotely");

        resetadminpasswordbutton.setText("Change");
        resetadminpasswordbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetadminpasswordbuttonActionPerformed(evt);
            }
        });

        getadminpasswordButton.setText("Toggle visibility");
        getadminpasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getadminpasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getadminpasswordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetadminpasswordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getadminpasswordButton)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetadminpasswordbutton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getadminpasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getadminpasswordButtonActionPerformed
        if (this.passwordField.getText().length() == 0) {
            this.passwordField.setText(Configuration.instance()
                    .getAdminPassword());
        } else {
            this.passwordField.setText("");
        }
    }//GEN-LAST:event_getadminpasswordButtonActionPerformed

    private void resetadminpasswordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetadminpasswordbuttonActionPerformed
        MainDialog.resetAdminPassword();
        this.passwordField.setText(Configuration.instance()
                .getAdminPassword());
    }//GEN-LAST:event_resetadminpasswordbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getadminpasswordButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton resetadminpasswordbutton;
    // End of variables declaration//GEN-END:variables
}
